import type { Metadata } from "next";
import { Geist, Geist_Mono, Fredoka, Lato } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fredoka = Fredoka({
  weight: "400",
  variable: "--font-fredoka",
  subsets: ["latin"],
});

const lato = Lato({
  weight: "400",
  variable: "--font-lato",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} ${fredoka.variable} ${lato.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
            <Header>
                <Navbar/>
            </Header>
            {children}
      </body>
    </html>
  );
}
