import type { Metadata } from "next";
import { Geist, Fredoka, Lato } from "next/font/google";
import "../app/globals.css";
import Providers from "./provider";
import { SectionObserverProvider } from "@/context/SectionObserverContext";
import { Toaster } from "react-hot-toast";

const geist = Geist({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist-sans",
});

const fredoka = Fredoka({
    weight: "400",
    variable: "--font-fredoka",
    subsets: ["latin"],
})

const lato = Lato({
    weight: "400",
    variable: "--font-lato",
    subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "MyAniMa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html 
        lang="en" 
        className={`${geist.variable} ${fredoka.variable} ${lato.variable} h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col`}>
        <Providers>
          <SectionObserverProvider>
            {children}
            <Toaster
              position="bottom-right"
              toastOptions={{
                className: "font-fredoka font-semibold",
              }}
            />
          </SectionObserverProvider>
        </Providers>
       
      </body>
    </html>
  );
}
